<?php

return [
    [
        'title' => 'Programs',
        'register_name' => 'echo_news',
        'singular' => 'News',
        'plural' => 'News',
        'slug' => 'news',
        'icon' => 'dashicons-megaphone',
        'has_image_modifier' => false,
        'has_taxonomies' => true,
        // 'has_archive' => false,
        // 'menu_position' => 30,
        // 'image_settings' => [
        //     'name' => 'echo-history',
        //     'width' => 600,
        //     'height' => 600,
        // ],
    ],
    [
        'title' => 'Tejano History',
        'register_name' => 'echo_history',
        'singular' => 'History',
        'plural' => 'Histories',
        'slug' => 'history',
        'icon' => 'dashicons-book-alt',
        'has_image_modifier' => false,
        'has_taxonomies' => true,
    ],
    [
        'title' => 'Special Events',
        'register_name' => 'echo_events',
        'singular' => 'Event',
        'plural' => 'Events',
        'slug' => 'events',
        'icon' => 'dashicons-calendar',
        'has_image_modifier' => false,
        'has_taxonomies' => true,
    ],
    [
        'title' => 'Programs',
        'register_name' => 'echo_programs',
        'singular' => 'Program',
        'plural' => 'Programs',
        'slug' => 'programs',
        'icon' => 'dashicons-list-view',
        'has_image_modifier' => false,
        'has_taxonomies' => true,
    ],
];
